-- GENERATED by scripts/gen-content-sql.ts from src/content/fallback.ts. Do not edit by hand.
-- Overwrites the portfolio content with the latest copy. Run after portfolio.sql.
-- Note: this replaces edits made in /admin for the rows listed here.

alter table public.portfolio_items drop constraint if exists portfolio_items_kind_check;
alter table public.portfolio_items add constraint portfolio_items_kind_check
  check (kind in ('project','experience','education','certification','skill_group','achievement'));

insert into public.portfolio_profile (id, name, short_name, handle, headline, location, bio, email, availability, github_url, linkedin_url, anghami_url, avatar_url, section_order)
values (1, 'Mostafa Kamal Shabara', 'Mostafa', 'afosh', 'AI & Informatics (Robotics) student · games, apps & hardware', 'Mansoura, Egypt', 'I''m an AI & Informatics (Robotics) student at Horus University in Egypt. I build across the stack: a 3D fishing game in Godot, mobile apps and an ESP32 health watch at hackathons, ML models for predictive maintenance, and contest solutions with the ICPC HUE community.', 'mk1440165@gmail.com', 'Open to internships & freelance', 'https://github.com/iiafosh', 'https://www.linkedin.com/in/mostafa-kamal-3731453a9/', null, null, array['featured', 'achievements', 'projects', 'experience', 'education', 'skills', 'certifications', 'guestbook']::text[])
on conflict (id) do update set
  name = excluded.name,
  short_name = excluded.short_name,
  handle = excluded.handle,
  headline = excluded.headline,
  location = excluded.location,
  bio = excluded.bio,
  email = excluded.email,
  availability = excluded.availability,
  github_url = excluded.github_url,
  linkedin_url = excluded.linkedin_url,
  anghami_url = excluded.anghami_url,
  avatar_url = excluded.avatar_url,
  section_order = excluded.section_order;

insert into public.portfolio_items (id, kind, title, subtitle, period, location, description, highlights, tags, url, repo_url, image_url, video_url, featured, sort_order, visible) values
('proj-fosh-and-fish', 'project', 'fosh&fish', 'My first game · Godot 4 + Blender', 'Oct 2026', null, 'A cozy top-down fishing game rebuilt from a Discord fishing bot I was hooked on. Cast, catch, sell, upgrade your rod and boat, and travel through 7 biomes from the River to the Abyss. Open source.', array['20 fish, 21 rods, 17 boats, 8 baits and 7 biomes, balanced against the original bot data', 'Ships to Web, Windows, Linux and Android from one Godot project', '3D assets from itch.io and Sketchfab, reworked and rendered through a scripted Blender pipeline', 'Headless simulation tests for mechanics and balance, plus an automated trailer pipeline']::text[], array['Godot 4', 'GDScript', 'Blender', 'Python', 'AI-assisted dev']::text[], 'https://iiafosh.github.io/fosh-and-fish/', 'https://github.com/iiafosh/fosh-and-fish', '/media/fosh-and-fish-cover.jpg', 'https://github.com/iiafosh/fosh-and-fish/releases/download/v0.1-beta/fosh-and-fish-trailer-16x9.mp4', true, 10, true),
('proj-respark', 'project', 'ReSpark', 'E-waste recycling app · Green Loop competition', 'Sep 2026', null, 'A website and mobile app for recycling e-waste on two fronts: students take apart old hardware projects and sell the parts to other students, and AI workloads get software strategies that cut the energy and water data centers burn.', array['3rd place in the Horus University round; qualified to represent HUE nationally', 'Built the mobile application with a teammate', '36-hour non-stop build sprint with a team of three']::text[], array['Mobile app', 'Web', 'Sustainability', 'Team of 3']::text[], 'https://www.linkedin.com/in/mostafa-kamal-3731453a9/recent-activity/all/', null, null, null, false, 20, true),
('proj-medical-watch', 'project', 'Smart Medical Watch', 'Hardware + software · Damietta Hackathon', 'Jul 2026', null, 'A wearable that counts steps and reads heart rate, then streams the data over Wi-Fi to a live web dashboard.', array['XIAO ESP32-C6 with a 1.28" round TFT, MPU6050 step counting, MAX30100 pulse sensor and GPS', 'Fixed unreliable pulse readings by adding 4.7kΩ pull-up resistors', 'My part: technical research and the LoRa link in the hardware']::text[], array['ESP32', 'Arduino', 'LoRa', 'Sensors', 'IoT dashboard']::text[], 'https://www.linkedin.com/in/mostafa-kamal-3731453a9/recent-activity/all/', null, null, null, false, 30, true),
('proj-robo-space', 'project', 'Robo-Space', 'Predictive maintenance with ML', 'Jun 2026', null, 'Analyzes industrial sensor data to predict machine failures before they happen, to cut downtime and repair costs.', array['Random Forest classifier detecting 6 types of machine failure', 'Interactive dashboard: live failure probabilities from temperature, RPM and torque inputs', 'ROC curves, feature importance and distribution plots, plus spoken text-to-speech alerts']::text[], array['Python', 'scikit-learn', 'Pandas', 'Tkinter', 'Matplotlib']::text[], 'https://www.linkedin.com/in/mostafa-kamal-3731453a9/recent-activity/all/', null, null, null, false, 40, true),
('proj-numlab', 'project', 'NumLab', 'Numerical methods solver · course project', 'Jun 2026', null, 'A desktop app that solves numerical methods problems. The team of six wrote all the math algorithms by hand in Python and used AI tools only for the CustomTkinter interface.', '{}'::text[], array['Python', 'Numerical methods', 'CustomTkinter']::text[], 'https://www.linkedin.com/in/mostafa-kamal-3731453a9/recent-activity/all/', null, null, null, false, 50, true),
('proj-afosh-ai', 'project', 'Afosh AI', 'Gemini chat assistant · MSC HUE session', '2026', null, 'A persona chatbot built for a Microsoft Student Club session at HUE: a street-smart tech mentor that explains Python, C++ and computer vision with an Egyptian twist.', array['Google Gemini API with a custom system persona', 'Auto-deploys with GitHub Actions']::text[], array['React', 'TypeScript', 'Gemini API', 'GitHub Actions']::text[], null, 'https://github.com/iiafosh/portfolie_for_MSC-mostsfs-kmal', null, null, false, 60, true),
('proj-portfolio', 'project', 'This portfolio', 'Full-stack web app', '2026', null, 'Content, ordering and the guestbook live in Supabase Postgres behind Row Level Security, with GitHub sign-in and an owner-only editor.', '{}'::text[], array['React', 'TypeScript', 'TanStack', 'Supabase', 'Tailwind']::text[], null, 'https://github.com/iiafosh/portfolio', null, null, false, 70, true),
('win-green-loop', 'achievement', '3rd place · Green Loop', 'Horus University round, with ReSpark', 'Sep 2026', null, 'Top 3 at HUE, qualified to represent the university in the national round.', '{}'::text[], '{}'::text[], 'https://www.linkedin.com/in/mostafa-kamal-3731453a9/recent-activity/all/', null, null, null, false, 10, true),
('win-ecpc', 'achievement', '#1 at Horus · ECPC qualifiers', 'ICPC HUE community', '2026', null, 'Top-ranked Horus team (189th overall), solving 4 problems in 5 hours as first-year students.', '{}'::text[], '{}'::text[], 'https://www.linkedin.com/in/mostafa-kamal-3731453a9/recent-activity/all/', null, null, null, false, 20, true),
('win-damietta', 'achievement', 'Qualified · Damietta Hackathon', 'With the Smart Medical Watch', 'Jul 2026', null, 'Passed the preliminaries in my first year and built a working hardware + software wearable on site.', '{}'::text[], '{}'::text[], 'https://www.linkedin.com/in/mostafa-kamal-3731453a9/recent-activity/all/', null, null, null, false, 30, true),
('exp-icpc-hue', 'experience', 'Competitive programmer', 'ICPC HUE community', '2026 — Present', 'Horus University', 'Training with one of the community’s 16 teams on algorithms and data structures for ICPC-style contests.', array['Team ranked #1 at Horus in the ECPC qualifiers']::text[], array['C++', 'Algorithms', 'Problem solving']::text[], null, null, null, null, false, 10, true),
('exp-axis', 'experience', 'Member', 'AXIS student club', 'Present', 'Horus University', null, '{}'::text[], '{}'::text[], null, null, null, null, false, 20, true),
('edu-hue', 'education', 'Horus University in Egypt (HUE)', 'Faculty of Artificial Intelligence · AI & Informatics (Robotics)', '2025 — Present', 'New Damietta, Egypt', null, '{}'::text[], '{}'::text[], 'https://horus.edu.eg', null, null, null, false, 10, true),
('skill-languages', 'skill_group', 'Languages', null, null, null, null, '{}'::text[], array['Python', 'C++', 'TypeScript', 'GDScript', 'SQL']::text[], null, null, null, null, false, 10, true),
('skill-ai', 'skill_group', 'AI & data', null, null, null, null, '{}'::text[], array['scikit-learn', 'Pandas', 'Matplotlib', 'Random Forest', 'LLM APIs (Gemini)', 'Computer vision (YOLO)']::text[], null, null, null, null, false, 20, true),
('skill-hardware', 'skill_group', 'Hardware & IoT', null, null, null, null, '{}'::text[], array['ESP32', 'Arduino IDE', 'LoRa', 'MPU6050 / MAX30100 sensors', 'GPS modules']::text[], null, null, null, null, false, 30, true),
('skill-games', 'skill_group', 'Games & 3D', null, null, null, null, '{}'::text[], array['Godot 4', 'Blender', 'Game balancing', 'Multi-platform export']::text[], null, null, null, null, false, 40, true),
('skill-web', 'skill_group', 'Web & apps', null, null, null, null, '{}'::text[], array['React', 'Vite', 'TanStack', 'Tailwind CSS', 'Supabase', 'PostgreSQL', 'Tkinter / CustomTkinter']::text[], null, null, null, null, false, 50, true),
('skill-tools', 'skill_group', 'Tools & ways of working', null, null, null, null, '{}'::text[], array['Git & GitHub', 'GitHub Actions', 'AI-assisted coding', 'Hackathon teamwork']::text[], null, null, null, null, false, 60, true)
on conflict (id) do update set
  kind = excluded.kind,
  title = excluded.title,
  subtitle = excluded.subtitle,
  period = excluded.period,
  location = excluded.location,
  description = excluded.description,
  highlights = excluded.highlights,
  tags = excluded.tags,
  url = excluded.url,
  repo_url = excluded.repo_url,
  image_url = excluded.image_url,
  video_url = excluded.video_url,
  featured = excluded.featured,
  sort_order = excluded.sort_order,
  visible = excluded.visible;
