// Generates supabase/content.sql from src/content/fallback.ts so the database
// and the local fallback never drift. Run: npm run content:sql
import { writeFileSync } from 'node:fs'
import { FALLBACK_ITEMS, FALLBACK_PROFILE } from '../src/content/fallback.ts'

const q = (v: unknown): string => {
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'boolean' || typeof v === 'number') return String(v)
  if (Array.isArray(v)) return v.length ? `array[${v.map(q).join(', ')}]::text[]` : `'{}'::text[]`
  return `'${String(v).replace(/'/g, "''")}'`
}

const p = FALLBACK_PROFILE
const profileCols = ['name', 'short_name', 'handle', 'headline', 'location', 'bio', 'email', 'availability', 'github_url', 'linkedin_url', 'anghami_url', 'avatar_url', 'section_order'] as const
const itemCols = ['id', 'kind', 'title', 'subtitle', 'period', 'location', 'description', 'highlights', 'tags', 'url', 'repo_url', 'image_url', 'video_url', 'featured', 'sort_order', 'visible'] as const

const sql = `-- GENERATED by scripts/gen-content-sql.ts from src/content/fallback.ts. Do not edit by hand.
-- Overwrites the portfolio content with the latest copy. Run after portfolio.sql.
-- Note: this replaces edits made in /admin for the rows listed here.

alter table public.portfolio_items drop constraint if exists portfolio_items_kind_check;
alter table public.portfolio_items add constraint portfolio_items_kind_check
  check (kind in ('project','experience','education','certification','skill_group','achievement'));

insert into public.portfolio_profile (id, ${profileCols.join(', ')})
values (1, ${profileCols.map((c) => q(p[c])).join(', ')})
on conflict (id) do update set
${profileCols.map((c) => `  ${c} = excluded.${c}`).join(',\n')};

insert into public.portfolio_items (${itemCols.join(', ')}) values
${FALLBACK_ITEMS.map((it) => `(${itemCols.map((c) => q(it[c])).join(', ')})`).join(',\n')}
on conflict (id) do update set
${itemCols.filter((c) => c !== 'id').map((c) => `  ${c} = excluded.${c}`).join(',\n')};
`

writeFileSync(new URL('../supabase/content.sql', import.meta.url), sql)
console.log(`wrote supabase/content.sql (${FALLBACK_ITEMS.length} items)`)
